"""
api/metrics.py
==============
Prometheus metrics exporter for the XG3 Badminton pricing service.

Exposes /metrics in Prometheus text format via prometheus_client.

Metrics:
  Counters:
    badminton_markets_generated_total{discipline, tier}       — markets priced
    badminton_bets_validated_total{outcome}                   — bets processed (accepted/rejected)
    badminton_live_updates_total{discipline}                  — live score updates ingested
    badminton_settlement_events_total{result}                 — graded events

  Gauges:
    badminton_active_matches                                  — currently live matches
    badminton_total_liability_gbp                             — aggregate book liability
    badminton_feed_error_rate                                 — feed error fraction [0,1]

  Histograms:
    badminton_reprice_latency_seconds{discipline, mode}       — p50/p95/p99 latency
    badminton_markov_compute_seconds                          — Markov DP solve time

ZERO hardcoded probabilities.
"""

from __future__ import annotations

import time
from contextlib import contextmanager
from typing import Generator, Optional

import structlog

logger = structlog.get_logger(__name__)

# ---------------------------------------------------------------------------
# Lazy import of prometheus_client — service degrades gracefully if missing
# ---------------------------------------------------------------------------
try:
    from prometheus_client import (
        Counter,
        Gauge,
        Histogram,
        generate_latest,
        CONTENT_TYPE_LATEST,
        CollectorRegistry,
        REGISTRY,
    )
    _PROMETHEUS_AVAILABLE = True
except ImportError:  # pragma: no cover
    _PROMETHEUS_AVAILABLE = False
    logger.warning("prometheus_client_not_installed", detail="metrics endpoint will return empty response")

# ---------------------------------------------------------------------------
# Metric definitions
# ---------------------------------------------------------------------------

if _PROMETHEUS_AVAILABLE:
    # Counters
    MARKETS_GENERATED = Counter(
        "badminton_markets_generated_total",
        "Total number of market sets generated by the pricing engine.",
        labelnames=["discipline", "tier"],
    )

    BETS_VALIDATED = Counter(
        "badminton_bets_validated_total",
        "Total bets processed through the validation pipeline.",
        labelnames=["outcome"],   # "accepted" | "rejected"
    )

    LIVE_UPDATES = Counter(
        "badminton_live_updates_total",
        "Total live score update events ingested from the feed.",
        labelnames=["discipline"],
    )

    SETTLEMENT_EVENTS = Counter(
        "badminton_settlement_events_total",
        "Total settlement grading events.",
        labelnames=["result"],   # "graded" | "void" | "error"
    )

    # Gauges
    ACTIVE_MATCHES = Gauge(
        "badminton_active_matches",
        "Number of matches currently being priced (live or pre-match).",
    )

    TOTAL_LIABILITY_GBP = Gauge(
        "badminton_total_liability_gbp",
        "Current aggregate book liability across all active matches (GBP).",
    )

    FEED_ERROR_RATE = Gauge(
        "badminton_feed_error_rate",
        "Fraction of feed messages in the last window that were errors [0, 1].",
    )

    # Histograms
    REPRICE_LATENCY = Histogram(
        "badminton_reprice_latency_seconds",
        "Time to complete one full market reprice cycle (Markov + derivatives + margin).",
        labelnames=["discipline", "mode"],   # mode: "pre_match" | "live"
        buckets=[0.005, 0.010, 0.025, 0.050, 0.100, 0.200, 0.500, 1.0],
    )

    MARKOV_COMPUTE = Histogram(
        "badminton_markov_compute_seconds",
        "Time for the Markov DP engine to compute match probabilities.",
        buckets=[0.0001, 0.0005, 0.001, 0.005, 0.010, 0.050],
    )


# ---------------------------------------------------------------------------
# Helper: observe reprice latency
# ---------------------------------------------------------------------------

@contextmanager
def observe_reprice(discipline: str, mode: str) -> Generator[None, None, None]:
    """
    Context manager to record reprice latency.

    Usage::

        with observe_reprice("MS", "live"):
            ... run reprice ...
    """
    if not _PROMETHEUS_AVAILABLE:
        yield
        return

    t0 = time.perf_counter()
    try:
        yield
    finally:
        elapsed = time.perf_counter() - t0
        REPRICE_LATENCY.labels(discipline=discipline, mode=mode).observe(elapsed)


@contextmanager
def observe_markov() -> Generator[None, None, None]:
    """Context manager to record Markov DP compute time."""
    if not _PROMETHEUS_AVAILABLE:
        yield
        return

    t0 = time.perf_counter()
    try:
        yield
    finally:
        elapsed = time.perf_counter() - t0
        MARKOV_COMPUTE.observe(elapsed)


# ---------------------------------------------------------------------------
# Counter increments (thin wrappers for clean call sites)
# ---------------------------------------------------------------------------

def inc_markets_generated(discipline: str, tier: str) -> None:
    if _PROMETHEUS_AVAILABLE:
        MARKETS_GENERATED.labels(discipline=discipline, tier=tier).inc()


def inc_bet_accepted() -> None:
    if _PROMETHEUS_AVAILABLE:
        BETS_VALIDATED.labels(outcome="accepted").inc()


def inc_bet_rejected(reason: str = "rejected") -> None:
    if _PROMETHEUS_AVAILABLE:
        BETS_VALIDATED.labels(outcome="rejected").inc()


def inc_live_update(discipline: str) -> None:
    if _PROMETHEUS_AVAILABLE:
        LIVE_UPDATES.labels(discipline=discipline).inc()


def inc_settlement(result: str) -> None:
    """result: 'graded' | 'void' | 'error'"""
    if _PROMETHEUS_AVAILABLE:
        SETTLEMENT_EVENTS.labels(result=result).inc()


# ---------------------------------------------------------------------------
# Gauge setters
# ---------------------------------------------------------------------------

def set_active_matches(n: int) -> None:
    if _PROMETHEUS_AVAILABLE:
        ACTIVE_MATCHES.set(n)


def set_total_liability(liability_gbp: float) -> None:
    if _PROMETHEUS_AVAILABLE:
        TOTAL_LIABILITY_GBP.set(liability_gbp)


def set_feed_error_rate(rate: float) -> None:
    if _PROMETHEUS_AVAILABLE:
        FEED_ERROR_RATE.set(max(0.0, min(1.0, rate)))


# ---------------------------------------------------------------------------
# FastAPI route handler
# ---------------------------------------------------------------------------

def metrics_response() -> tuple[bytes, str]:
    """
    Generate the Prometheus metrics payload for the /metrics endpoint.

    Returns (body: bytes, content_type: str).
    """
    if not _PROMETHEUS_AVAILABLE:
        return b"# prometheus_client not installed\n", "text/plain; version=0.0.4"

    body = generate_latest(REGISTRY)
    return body, CONTENT_TYPE_LATEST
